#spring:
#  application:
#    name: product-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/product
#    username: pranshukk
#    password: pranshukk
#  jpa:
#    database: POSTGRESQL
#    # JPA / Hibernate
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
##  h2:
##    console:
##      enabled: true
##  datasource:
##    url: jdbc:h2:mem:test
##  jpa:
##    show-sql: true
##    hibernate:
##      ddl-auto: create
#
#server:
#  port: 8081
#
#

spring:
  application:
    name: product-service

  datasource:
#    url: jdbc:postgresql://localhost:5432/product
    url: jdbc:postgresql://ep-weathered-mud-aiub0wwh-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_dJuWzT1MX8YP

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
