spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: pranshukk
    password: pranshukk
  jpa:
    database: POSTGRESQL
    # JPA / Hibernate
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8081


